name: Deploy Website

on:
  push:
    branches:
      - main  # adjust if using master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Restart app with PM2 (zero-downtime)
        run: |
          pm2 start "npm start -- -p 5700" --name Scalixity-Website || pm2 restart Scalixity-Website
